# assets/strings.py

STRINGS = {
    "ru": {
        "app_title": "YT LOADER PRO v2.5",
        "tab_home": "Загрузка",
        "tab_history": "История",
        "tab_settings": "Настройки",
        "url_label": "URL Видео",
        "url_hint": "Вставьте ссылку...",
        "add_btn": "ДОБАВИТЬ",
        "queue_title": "Очередь загрузки",
        "queue_empty": "Очередь пуста",
        "clear_queue": "Очистить все",
        "status_ready": "Готов к работе",
        "status_downloading": "Загрузка...",
        "status_processing": "Обработка...",
        "status_finished": "Готово!",
        "error_url": "Некорректная ссылка",
        "error_generic": "Ошибка",
        "settings_title": "Настройки",
        "theme_dark": "Темная тема",
        "folder_download": "Папка загрузок",
        "lang_label": "Язык интерфейса",
        "proxy_label": "Proxy URL",
        "cookies_label": "Файл Cookies (Netscape)",
        "clear_history": "Очистить историю",
        "history_cleared": "История очищена",
        "open_folder_check": "Открыть папку после",
        "audio_only_switch": "Только аудио",
        "playlist_switch": "Плейлист",
        "eta": "Ост.",
        "quality_loading": "Анализ...",
        "quality_best": "Максимальное",
        # --- NEW ---
        "browser_cookies_label": "Куки из браузера",
        "browser_none": "Не использовать",
        "update_ytdlp_btn": "Обновить yt-dlp",
        "update_success": "yt-dlp успешно обновлен!",
        "update_error": "Ошибка обновления",
        "monitor_clipboard": "Следить за буфером",
        "subs_switch": "Субтитры",
        "embed_meta_switch": "Вшить метаданные",
        "system_section": "Система",
    },
    "en": {
        "app_title": "YT LOADER PRO v2.5",
        "tab_home": "Download",
        "tab_history": "History",
        "tab_settings": "Settings",
        "url_label": "Video URL",
        "url_hint": "Paste link here...",
        "add_btn": "ADD TO QUEUE",
        "queue_title": "Download Queue",
        "queue_empty": "Queue is empty",
        "clear_queue": "Clear All",
        "status_ready": "Ready",
        "status_downloading": "Downloading...",
        "status_processing": "Processing...",
        "status_finished": "Done!",
        "error_url": "Invalid URL",
        "error_generic": "Error",
        "settings_title": "Settings",
        "theme_dark": "Dark Mode",
        "folder_download": "Download Folder",
        "lang_label": "Interface Language",
        "proxy_label": "Proxy URL",
        "cookies_label": "Cookies File (Netscape)",
        "clear_history": "Clear History",
        "history_cleared": "History Cleared",
        "open_folder_check": "Open folder after",
        "audio_only_switch": "Audio Only",
        "playlist_switch": "Playlist",
        "eta": "ETA",
        "quality_loading": "Analyzing...",
        "quality_best": "Best Available",
        # --- NEW ---
        "browser_cookies_label": "Browser Cookies",
        "browser_none": "Do not use",
        "update_ytdlp_btn": "Update yt-dlp",
        "update_success": "yt-dlp updated successfully!",
        "update_error": "Update failed",
        "monitor_clipboard": "Monitor Clipboard",
        "subs_switch": "Subtitles",
        "embed_meta_switch": "Embed Metadata",
        "system_section": "System",
    }
}